[package]
name = "ddtri"
version = "0.1.0"
edition = "2021"
description = "Distance Difference Triangulation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.27.0", features = ["rand"] }
rand = "0.8.5"
